//
// main.cpp
// Main file
// ----------------------------------
// Developed with embedXcode+
// https://embedXcode.weebly.com
//
// Project 		MidiRouter_Lib
//
// Created by 	Kurt Arnlund, 4/14/20 8:08 PM
//              Kurt Arnlund
//
// Copyright 	© Kurt Arnlund, 2020
// Licence 		GNU General Public Licence
//
// See 			MidiRouter_Lib.ino and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN MidiRouter_Lib.ino
// ----------------------------------
//
// Last update: Jun 30, 2017 release 7.5.0

// IDE selection
#if defined(EMBEDXCODE)

// Core library and main()
// Minimal proxy main() to be updated at build
#include "Arduino.h"

int main(void)
{
    setup();

    for (;;)
    {
        loop();
    }

    return 0;
}

// Sketch
#include "MidiRouter_Lib.ino"


#endif                                                                          // end embedXcode

